# QRNN Training

In [1]:
%load_ext autoreload
%autoreload 2
%env KERAS_BACKEND=tensorflow

import numpy as np
import matplotlib_settings
from typhon.retrieval.qrnn import QRNN

env: KERAS_BACKEND=tensorflow


Using TensorFlow backend.


In [2]:
x_train = np.load("data/x_train_5.npy")
y_train = np.load("data/y_train_5.npy")
x_mean  = x_train.mean(axis=0, keepdims=True)
x_sigma = x_train.std(axis=0,  keepdims=True)

In [3]:
x_train.shape

(10000, 5)

In [4]:
quantiles = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
qrnn = QRNN(5, quantiles, 2, 256)

In [5]:
qrnn.fit(x_train, y_train, 1.0)

Epoch 1/200
17/17 [==============================] - 0s - loss: 40.4321 - val_loss: 7.7970
Epoch 2/200
17/17 [==============================] - 0s - loss: 19.3145 - val_loss: 53.1140
Epoch 3/200
17/17 [==============================] - 0s - loss: 21.8985 - val_loss: 10.9789
Epoch 4/200
17/17 [==============================] - 0s - loss: 18.0767 - val_loss: 13.5530
Epoch 5/200
17/17 [==============================] - 0s - loss: 17.8018 - val_loss: 15.3350
Epoch 6/200
17/17 [==============================] - 0s - loss: 15.0296 - val_loss: 29.6240
Epoch 7/200
12/17 [====================>.........] - ETA: 0s - loss: 15.3429
 Reduced learning rate to 0.1
17/17 [==============================] - 0s - loss: 14.8940 - val_loss: 16.5551
Epoch 8/200
17/17 [==============================] - 0s - loss: 7.2336 - val_loss: 14.8648
Epoch 9/200
17/17 [==============================] - 0s - loss: 7.4840 - val_loss: 19.2207
Epoch 10/200
17/17 [==============================] - 0s - loss: 7.8074 - val_lo

17/17 [==============================] - 0s - loss: 2.1076 - val_loss: 63.9238
Epoch 77/200
17/17 [==============================] - 0s - loss: 2.0909 - val_loss: 65.1902
Epoch 78/200
17/17 [==============================] - 0s - loss: 2.1024 - val_loss: 65.6301
Epoch 79/200
11/17 [==================>...........] - ETA: 0s - loss: 2.1386
 Reduced learning rate to 2.44141e-05
17/17 [==============================] - 0s - loss: 2.1015 - val_loss: 66.6027
Epoch 80/200
17/17 [==============================] - 0s - loss: 2.1009 - val_loss: 66.8938
Epoch 81/200
17/17 [==============================] - 0s - loss: 2.1285 - val_loss: 67.7206
Epoch 82/200
17/17 [==============================] - 0s - loss: 2.0908 - val_loss: 68.8498
Epoch 83/200
17/17 [==============================] - 0s - loss: 2.1327 - val_loss: 69.8440
Epoch 84/200
17/17 [==============================] - 0s - loss: 2.1335 - val_loss: 70.3484
Epoch 85/200
12/17 [====================>.........] - ETA: 0s - loss: 2.1003
 Reduc

12/17 [====================>.........] - ETA: 0s - loss: 2.0327
 Reduced learning rate to 5.96046e-09
17/17 [==============================] - 0s - loss: 2.0792 - val_loss: 99.5169


In [6]:
np.mean(x_train, axis = 0, keepdims = True)

array([[ 146.50474944,  175.760782  ,  237.33642253,  265.90076508,
         260.36461048]])

In [7]:
qrnn.save("qrnn")

In [9]:
qrnn2 = QRNN.load("qrnn")

In [12]:
qrnn2.predict(x_train)

array([[  19.57834053,   19.84030342,   20.02257347, ...,   20.54763794,
          20.69142914,   20.92699623],
       [   5.39958239,    5.50286007,    5.63548851, ...,    6.08992863,
           6.21165657,    6.46132946],
       [  18.81868744,   19.14671898,   19.39114952, ...,   20.0328331 ,
          20.06956291,   20.42111206],
       ..., 
       [  12.26674557,   12.62013435,   12.75143719, ...,   13.25910473,
          13.46760368,   13.74556065],
       [  23.78139305,   24.09221458,   24.34200096, ...,   24.96905899,
          25.17671967,   25.54310799],
       [ 124.22517395,  126.38543701,  127.82956696, ...,  134.44300842,
         136.72247314,  140.0385437 ]], dtype=float32)

In [13]:
y_train

array([  20.18334057,    5.83043859,   19.32219261, ...,   13.12114782,
         24.40540452,  139.03744003])